export const productsList = [
    {
        id: 1,
        name: "My Smart Defense SPF50 Sunscreen Fluid 50ml",
        price: 299,
        image: "assets/images/01.jpg",
        rating: 4.9,
    },
    {
        id: 2,
        name: "TWS (True Wireless Stereo) P49v5.3",
        price: 349,
        image: "assets/images/02.jpg",
        rating: 4.4,
    },
    {
        id: 3,
        name: "Samsung Galaxy A35 Dual SIM 256GB and 8GB RAM mobile phone",
        price: 2410,
        image: "assets/images/03.jpg",
        rating: 4.4,
    },
    {
        id: 4,
        name: "Hammering Screwdrivers Set, 7 PCS, CR-V",
        price: 99,
        image: "assets/images/04.jpg",
        rating: 4.9,
    },
    {
        id: 5,
        name: "Ronix RH-2102, 12pcs Combination Spanner Set",
        price: 1490,
        image: "assets/images/05.jpg",
        rating: 4.4,
    },
    {
        id: 6,
        name: "Zebronics Zeb-Paradise Bluetooth Wired Over Ear",
        price: 199,
        image: "assets/images/06.jpg",
        rating: 4.4,
    },
    {
        id: 7,
        name: "Green Lion Ocean Open Ear Headphones",
        price: 190,
        image: "assets/images/07.jpg",
        rating: 4.9,
    },
    {
        id: 8,
        name: "Galaxy wireless headphones duwo",
        price: 219,
        image: "assets/images/08.jpg",
        rating: 4.0,
    },
    {
        id: 9,
        name: "RL2 Pro Reolink Smart Watch",
        price: 350,
        image: "assets/images/09.jpg",
        rating: 4.4,
    },
    {
        id: 10,
        name: "Duwo Flamingo Bluetooth Headphone",
        price: 160,
        image: "assets/images/10.jpg",
        rating: 3.9,
    },
    {
        id: 11,
        name: "Sony PlayStation 5 Slim Console 1TB Region 2016A Europe with additional Controller",
        price: 2300,
        image: "assets/images/11.jpg",
        rating: 4.4,
    },
    {
        id: 12,
        name: "Caspian Super-MMT Fuel Supplement 300 ml",
        price: 120,
        image: "assets/images/12.jpg",
        rating: 4.4,
    }
];
